# Generated by Django 5.1.1 on 2024-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/')),
            ],
        ),
    ]
